### ISSUE TITLE
Add More Articles,Info For all Assignments

### ISSUE THREAD

**Issue by nakul1010** [nakul1010/Assignments#1]

**Comment by Atharva-14** [comment]
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes

def paddedText(text):
  while len(text) % 16 != 0:
    text += ' '
  return text

plain_input = input("Enter the text to be encrypted: ")
plain = paddedText(plain_input)

key = get_random_bytes(16)

cipher = AES.new(key)
ciphertext = cipher.encrypt(plain)
print(ciphertext)
cleartext = cipher.decrypt(ciphertext)
print(cleartext)
